package com.example.pricefinder;
import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.pdf.*;import android.net.*;import android.provider.OpenableColumns;import android.database.Cursor;import android.content.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;import java.util.concurrent.*;import java.util.regex.*;
public class MainActivity extends Activity{
 Db db; LinearLayout results; EditText search; TextView status; ExecutorService pool=Executors.newSingleThreadExecutor();
 public void onCreate(Bundle b){super.onCreate(b);db=new Db(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,24,24,24);
 TextView title=new TextView(this);title.setText("جستجوی قیمت کالا");title.setTextSize(24);root.addView(title);
 LinearLayout bar=new LinearLayout(this);Button imp=new Button(this);imp.setText("افزودن PDF / عکس");bar.addView(imp,new LinearLayout.LayoutParams(0,-2,1));Button go=new Button(this);go.setText("جستجو");bar.addView(go,new LinearLayout.LayoutParams(0,-2,1));root.addView(bar);
 search=new EditText(this);search.setHint("کد یا نام کالا...");root.addView(search);status=new TextView(this);root.addView(status);ScrollView sv=new ScrollView(this);results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);sv.addView(results);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
 imp.setOnClickListener(v->pick());go.setOnClickListener(v->show(search.getText().toString().trim()));}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,10);}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r!=10||c!=RESULT_OK||d==null)return;ArrayList<Uri> u=new ArrayList<>();if(d.getClipData()!=null)for(int i=0;i<d.getClipData().getItemCount();i++)u.add(d.getClipData().getItemAt(i).getUri());else if(d.getData()!=null)u.add(d.getData());pool.execute(()->{for(Uri x:u)process(x);runOnUiThread(()->status.setText("پردازش تمام شد."));});}
 String name(Uri u){Cursor c=getContentResolver().query(u,null,null,null,null);if(c!=null){try{if(c.moveToFirst()){int x=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(x>=0)return c.getString(x);}}finally{c.close();}}return "file";}
 String ocr(Bitmap b)throws Exception{File dir=new File(getFilesDir(),"tessdata");if(!dir.exists())dir.mkdirs();Ocr o=new Ocr();if(!o.init(getFilesDir()))return "";String s=o.read(b);o.close();return s;}
 void process(Uri u){String n=name(u);try{if(n.toLowerCase(Locale.US).endsWith(".pdf"))pdf(u,n);else image(u,n);}catch(Exception e){runOnUiThread(()->status.setText("خطا: "+e.getMessage()));}}
 void pdf(Uri u,String n)throws Exception{ParcelFileDescriptor p=getContentResolver().openFileDescriptor(u,"r");PdfRenderer f=new PdfRenderer(p);db.clearSource(n);for(int i=0;i<f.getPageCount();i++){PdfRenderer.Page pg=f.openPage(i);Bitmap b=Bitmap.createBitmap(pg.getWidth()*2,pg.getHeight()*2,Bitmap.Config.ARGB_8888);b.eraseColor(Color.WHITE);pg.render(b,null,null,PdfRenderer.Page.RENDER_MODE_FOR_PRINT);pg.close();save(ocr(b),n,i+1);b.recycle();int z=i+1;runOnUiThread(()->status.setText("صفحه "+z+" در حال پردازش..."));}f.close();p.close();}
 void image(Uri u,String n)throws Exception{Bitmap b=BitmapFactory.decodeStream(getContentResolver().openInputStream(u));if(b==null)return;db.clearSource(n);save(ocr(b),n,1);b.recycle();}
 void save(String t,String s,int pg){Pattern p=Pattern.compile("\\b[A-Z]{1,8}[A-Z0-9]{1,14}(?:-[A-Z0-9]+)*\\b");Matcher m=p.matcher(t==null?"":t);boolean any=false;while(m.find()){String code=m.group();String x=t.substring(Math.max(0,m.start()-150),Math.min(t.length(),m.end()+350)).replace("\n"," ");db.add(code,x,price(x),s,pg,x);any=true;}if(!any&&!t.trim().isEmpty())db.add("",t.substring(0,Math.min(1000,t.length())),"",s,pg,t);}
 String price(String s){Matcher m=Pattern.compile("(?<![A-Za-z])\\d{4,15}(?![A-Za-z])").matcher(s.replace(",","").replace("٬",""));String x="";while(m.find())x=m.group();return x;}
 void show(String q){results.removeAllViews();if(q.isEmpty())return;for(String[] x:db.search(q)){TextView t=new TextView(this);t.setText("کد: "+x[0]+"\nنام: "+x[1]+"\nقیمت: "+x[2]+"\nمنبع: "+x[3]+" | صفحه: "+x[4]);t.setTextSize(17);t.setPadding(12,16,12,16);results.addView(t);}}
 protected void onDestroy(){pool.shutdownNow();super.onDestroy();}
}
